server:
  port: 8085

spring:
  application:
    name: inventory-service

  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8089}/"

  datasource:
    url: jdbc:mysql://localhost:3307/inventory_db
    username: root
    password: mysql123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

clients:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8762/eureka/}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
