server:
  port: 8086

spring:
  application:
    name: order-service

  config:
    import: "optional:configserver:http://localhost:8089"

  datasource:
    url: jdbc:mysql://localhost:3307/orders_db
    username: root
    password: mysql123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
