server:
  port: 8085

spring:
  cloud:
    discovery:
      enabled: true

clients:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8084}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8762/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:inventory-service}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      productService:
        maxAttempts: 2
        waitDuration: 1s

  ratelimiter:
    instances:
      productService:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 10s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

  timelimiter:
    instances:
      productService:
        timeoutDuration: 2s
        cancelRunningFuture: true

  bulkhead:
    instances:
      productService:
        maxWaitDuration: 5s
        maxConcurrentCalls: 5
