server:
  port: 8061

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8089"

jwt:
  secret: ESTA_ES_UNA_CLAVE_SECRETA_MUY_LARGA_PARA_FIRMAR_TOKENS_123456
